# Generated by Django 6.0.5 on 2026-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_alter_artist_bio_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(choices=[('Oil on Canvas', 'Oil on Canvas'), ('Watercolor', 'Watercolor'), ('Sculpture', 'Sculpture'), ('Drawings', 'Drawings')], max_length=100),
        ),
    ]
